In [4]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 1.08559715 11.57623868  6.30066314  3.75021378 19.96713616 16.69584533
 17.53379504 18.71371071 18.83256996 16.66385945 17.90107257 11.42516598
 18.13583381 10.1593461   4.08738795 19.02571049  1.16908411 15.46785569
 12.32275242 18.91997366]




[[ 1.08559715 11.57623868  6.30066314  3.75021378 19.96713616]
 [16.69584533 17.53379504 18.71371071 18.83256996 16.66385945]
 [17.90107257 11.42516598 18.13583381 10.1593461   4.08738795]
 [19.02571049  1.16908411 15.46785569 12.32275242 18.91997366]]


[[ 1.08559715 11.57623868  6.30066314  3.75021378  0.        ]
 [16.69584533 17.53379504 18.71371071  0.         16.66385945]
 [17.90107257 11.42516598  0.         10.1593461   4.08738795]
 [ 0.          1.16908411 15.46785569 12.32275242 18.91997366]]
